name: workmanager_tester
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  workmanager: ^0.7.0
  flutter_fgbg: ^0.7.1
  path_provider: ^2.1.5
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
